package koopa.tokenizers.cobol.tags;

public enum SyntacticTag {
	STRING_LITERAL, DECIMAL_LITERAL, BOOLEAN_LITERAL, HEXADECIMAL_LITERAL, CHARACTER_STRING, SEPARATOR, PICTURE, INTEGER_LITERAL, SIGNED, UNSIGNED, PSEUDO_LITERAL
}
