name = KoopaLoggingConfig

# Console appender
appender.CONSOLE.type = Console
appender.CONSOLE.name = CONSOLE
appender.CONSOLE.layout.type = PatternLayout
appender.CONSOLE.layout.pattern = [%t:%p] %c: %m%n

# Root logger
rootLogger.level = ERROR
rootLogger.appenderRef.CONSOLE.ref = CONSOLE

# Uncomment to see what's going on in the line splitting stage.
# logger.linesplitter.name = source.linesplitter
# logger.linesplitter.level = TRACE

# Uncomment to see how source format directives are being handled.
# logger.source_format_directives.name = source.cobol.source_format_directives
# logger.source_format_directives.level = TRACE

# Uncomment to see what's going on in the compiler directives tokenizer stage.
# logger.compiler_directives.name = source.cobol.compiler_directives
# logger.compiler_directives.level = TRACE

# Uncomment to see what's going on in the program area tokenizing stage.
# logger.program_area.name = source.cobol.program_area
# logger.program_area.level = TRACE

# Uncomment to see what's going on in the source formatting directives filter stage.
# logger.source_listing.name = source.cobol.source_listing
# logger.source_listing.level = TRACE

# Uncomment to see what's going on in the continuations tokenizing stage.
# logger.continuations.name = source.cobol.continuations
# logger.continuations.level = TRACE

# Uncomment to see what's going on in the inline comments tokenizer stage.
# logger.inline_comments.name = source.cobol.inline_comments
# logger.inline_comments.level = TRACE

# Uncomment to see what's going on in the preprocessing tokenizer stage.
# Choose DEBUG for info on preprocessing directives.
# Choose TRACE to see the actual tokens being generated.
# logger.replacing.name = source.cobol.replacing
# logger.replacing.level = TRACE
# logger.replacing_matching.name = source.cobol.replacing.matching
# logger.replacing_matching.level = TRACE
# logger.replacing_leading.name = source.cobol.replacing.leading
# logger.replacing_leading.level = TRACE
# logger.replacing_trailing.name = source.cobol.replacing.trailing
# logger.replacing_trailing.level = TRACE
#
# logger.copy_include.name = source.cobol.copy_include
# logger.copy_include.level = TRACE
# logger.cobol_replace.name = source.cobol.replace
# logger.cobol_replace.level = TRACE
# logger.replacing.level = DEBUG

# Uncomment to see how copybooks are being matched.
# Set to TRACE to see individual tests. INFO for high-level results.
# logger.copybooks.name = copybooks
# logger.copybooks.level = INFO

# Uncomment to see what's going on in the test tokenizer stage.
# logger.source_test.name = source.test
# logger.source_test.level = TRACE

# Uncomment to see what optimizations are being applied.
# logger.optimization.name = optimization
# logger.optimization.level = TRACE

# Uncomment to see what's going on with the grammar.
# logger.grammar.name = grammar
# logger.grammar.level = TRACE

# XPath evaluation.
# logger.xpath.name = xpath
# logger.xpath.level = TRACE

# Encoding related info.
# logger.encoding.name = encoding
# logger.encoding.level = TRACE

# Line ending related info.
# logger.eoln.name = eoln
# logger.eoln.level = TRACE

# KG generation logging.
# logger.kg_generation.name = kg.generation
# logger.kg_generation.level = TRACE