package koopa.core.data;

/**
 * This is the secondary piece of data which gets generated by Koopa. It
 * provides more context on how {@linkplain Token}s are being used in an input.
 */
public abstract class Marker implements Data {

	/**
	 * Each marker has a name, which can be used to identify it in more detail.
	 */
	public abstract String getName();
}
